# -*- coding: utf-8 -*-
"""ML_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kaeew7fGKZgb8SCQUxDIkyw8_BoiGs6u
"""

spark

# This cell loads the final ML-ready dataset from GCS.
# The dataset already contains engineered numeric features
# and one-hot encoded vectors, so no preprocessing is done here.

final_df = spark.read.parquet(
    "gs://game-scape/gold/final_ml_dataset_single/part-00000-d0510ba9-ba10-44ee-93cd-284d27dd20bf-c000.snappy.parquet"
)

# This cell verifies the schema of the ML dataset.
# This does not trigger a Spark job.

final_df.printSchema()

# This cell prepares the final ML dataset for cold-start sentiment prediction.
# The target is the game-level positive review rate (pos_rate).
# Features are restricted to metadata and non-review-derived attributes only,
# ensuring no leakage from user sentiment into the input space.

from pyspark.ml.feature import VectorAssembler

# Target variable
label_col = "pos_rate"

# Numeric metadata features (safe for cold-start prediction)
numeric_features = [
    "avg_playtime_hours",   # engagement proxy
    "price",
    "required_age"
]

# Multi-hot encoded categorical metadata
vector_features = [
    "genres_vec",
    "categories_vec",
    "tags_vec"
]

# Assemble all usable features into a single feature vector
assembler = VectorAssembler(
    inputCols=numeric_features + vector_features,
    outputCol="features",
    handleInvalid="skip"
)

ml_df = assembler.transform(final_df)

# Select only the columns required for Spark ML training
ml_df = ml_df.select(
    "appid",
    "game",
    label_col,
    "features"
)

# Cache once since this dataset will be reused across models
ml_df = ml_df.persist()

print(f"Final ML row count: {ml_df.count():,}")
ml_df.printSchema()

# This cell splits the ML dataset into train and test sets.
# A fixed seed is used to make results reproducible.

train_df, test_df = ml_df.randomSplit([0.8, 0.2], seed=42)

print(f"Train rows: {train_df.count():,}")
print(f"Test rows:  {test_df.count():,}")

# This cell trains a baseline linear regression model
# to predict pos_rate from numeric metadata features.

from pyspark.ml.regression import LinearRegression

lr = LinearRegression(
    featuresCol="features",
    labelCol="pos_rate",
    maxIter=50,
    regParam=0.1,
    elasticNetParam=0.0
)

lr_model = lr.fit(train_df)

print("Model training complete")

# This cell runs inference on the test dataset.

pred_df = lr_model.transform(test_df)

pred_df.select(
    "pos_rate",
    "prediction"
).show(5, truncate=False)

# This cell computes standard regression metrics.

from pyspark.ml.evaluation import RegressionEvaluator

evaluator_rmse = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="rmse"
)

evaluator_mae = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="mae"
)

evaluator_r2 = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="r2"
)

rmse = evaluator_rmse.evaluate(pred_df)
mae = evaluator_mae.evaluate(pred_df)
r2 = evaluator_r2.evaluate(pred_df)

print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mae:.4f}")
print(f"R²:   {r2:.4f}")

# This cell trains a Linear Regression model to predict game-level positive
# review rate (pos_rate) using metadata-derived features and evaluates
# model quality using standard regression metrics and diagnostic plots.
#
# Target:
# pos_rate → fraction of positive reviews per game
#
# Features:
# - Numeric: avg_playtime_hours, price, required_age
# - Encoded metadata: genres_vec, categories_vec, tags_vec
#
# The goal here is not to build a perfect model, but to:
# 1. Establish a stable baseline
# 2. Verify signal exists in metadata
# 3. Inspect prediction behavior visually

from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator
import matplotlib.pyplot as plt

# Split data into train and test sets
train_df, test_df = ml_df.randomSplit([0.8, 0.2], seed=42)

# Configure Linear Regression
# - Ridge regularization to control coefficient magnitude
# - Standardization enabled for numeric stability
lr = LinearRegression(
    featuresCol="features",
    labelCol="pos_rate",
    regParam=0.01,
    elasticNetParam=0.0,
    maxIter=50,
    tol=1e-6,
    standardization=True
)

# Train model
lr_model = lr.fit(train_df)

# Generate predictions
predictions = lr_model.transform(test_df)

# Evaluate regression quality
rmse = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="rmse"
).evaluate(predictions)

mae = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="mae"
).evaluate(predictions)

r2 = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="r2"
).evaluate(predictions)

print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R²  : {r2:.4f}")
print(f"Intercept: {lr_model.intercept:.4f}")
print(f"Total coefficients: {len(lr_model.coefficients)}")



# This cell visualizes model predictions against actual values
# to understand model fit, bias, and error behavior.

# Plot 1: Predicted vs actual positive rate
plt.figure(figsize=(7, 6))

plt.scatter(
    plot_df["pos_rate"],
    plot_df["prediction"],
    color="blue",
    alpha=0.5,
    s=12,
    label="Predicted"
)

plt.plot(
    [0, 1],
    [0, 1],
    color="red",
    linewidth=2,
    label="Ideal fit"
)

plt.xlabel("Actual Positive Rate")
plt.ylabel("Predicted Positive Rate")
plt.title("Predicted vs Actual Positive Rate")
plt.legend()
plt.show()

# Plot 2: Distribution of actual vs predicted values
plt.figure(figsize=(7, 4))

plt.hist(
    plot_df["pos_rate"],
    bins=40,
    alpha=0.6,
    color="green",
    label="Actual"
)

plt.hist(
    plot_df["prediction"],
    bins=40,
    alpha=0.6,
    color="orange",
    label="Predicted"
)

plt.xlabel("Positive Rate")
plt.ylabel("Count")
plt.title("Actual vs Predicted Distribution")
plt.legend()
plt.show()

# Plot 3: Residual analysis
residuals = plot_df["prediction"] - plot_df["pos_rate"]

plt.figure(figsize=(7, 4))

plt.scatter(
    plot_df["pos_rate"],
    residuals,
    color="purple",
    alpha=0.5,
    s=12
)

plt.axhline(0, color="black")

plt.xlabel("Actual Positive Rate")
plt.ylabel("Residual (Predicted - Actual)")
plt.title("Residuals vs Actual Positive Rate")
plt.show()

# This cell trains a Gradient Boosted Tree regression model to predict
# game-level positive review rate and evaluates its performance using
# standard regression metrics and diagnostic visualizations.

from pyspark.ml.regression import GBTRegressor
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.sql.functions import col
import matplotlib.pyplot as plt

# Split data into train and test sets
train_df, test_df = ml_df.randomSplit([0.8, 0.2], seed=42)

# Gradient Boosted Trees model
# maxDepth controls tree complexity
# maxIter controls number of boosting rounds
# stepSize controls learning rate
gbt = GBTRegressor(
    labelCol="pos_rate",
    featuresCol="features",
    maxDepth=6,
    maxIter=50,
    stepSize=0.1,
    subsamplingRate=0.8,
    seed=42
)

# Train the model
gbt_model = gbt.fit(train_df)

# Generate predictions
predictions = gbt_model.transform(test_df)

# Evaluate model performance
rmse_eval = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="rmse"
)

mae_eval = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="mae"
)

r2_eval = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="r2"
)

rmse = rmse_eval.evaluate(predictions)
mae = mae_eval.evaluate(predictions)
r2 = r2_eval.evaluate(predictions)

print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"R2: {r2:.4f}")



plot_df = (
    predictions
    .select("pos_rate", "prediction")
    .sample(fraction=0.3, seed=42)
    .limit(3000)
    .toPandas()
)

plt.figure(figsize=(7, 6))

plt.scatter(
    range(len(plot_df)),
    plot_df["pos_rate"],
    color="tab:green",
    alpha=0.6,
    s=12,
    label="Actual"
)

plt.scatter(
    range(len(plot_df)),
    plot_df["prediction"],
    color="tab:blue",
    alpha=0.6,
    s=12,
    label="Predicted"
)

plt.xlabel("Sample index")
plt.ylabel("Positive Rate")
plt.title("Actual vs Predicted Positive Rate")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

# This cell trains a RandomForest regression model to predict pos_rate
# using the assembled feature vector. It evaluates model performance
# and visualizes actual vs predicted values for sanity checking.

from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.sql.functions import col
import matplotlib.pyplot as plt

# Split data into train and test sets
train_df, test_df = ml_df.randomSplit([0.8, 0.2], seed=42)

# Define RandomForest regressor
rf = RandomForestRegressor(
    featuresCol="features",
    labelCol="pos_rate",
    predictionCol="prediction",
    numTrees=100,
    maxDepth=8,
    maxBins=64,
    seed=42
)

# Train the model
rf_model = rf.fit(train_df)

# Generate predictions
predictions = rf_model.transform(test_df).persist()

# Evaluate using regression metrics
rmse = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="rmse"
).evaluate(predictions)

r2 = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="r2"
).evaluate(predictions)

mae = RegressionEvaluator(
    labelCol="pos_rate",
    predictionCol="prediction",
    metricName="mae"
).evaluate(predictions)

print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mae:.4f}")
print(f"R2:   {r2:.4f}")


# Small, driver-safe sample
plot_df = (
    predictions
    .select("pos_rate", "prediction")
    .sample(fraction=0.15, seed=42)
    .limit(3000)
    .toPandas()
)

# Plot 1: Distribution of actual vs predicted
plt.figure(figsize=(6, 4))
plt.hist(plot_df["pos_rate"], bins=30, alpha=0.6, label="Actual", density=True)
plt.hist(plot_df["prediction"], bins=30, alpha=0.6, label="Predicted", density=True)
plt.xlabel("Positive Rate")
plt.ylabel("Density")
plt.title("Distribution: Actual vs Predicted")
plt.legend()
plt.grid(True)
plt.show()

# Plot 2: Binned calibration plot
plot_df["bin"] = (plot_df["pos_rate"] * 10).astype(int) / 10

calibration = (
    plot_df
    .groupby("bin")[["pos_rate", "prediction"]]
    .mean()
)

plt.figure(figsize=(6, 4))
plt.plot(calibration.index, calibration["pos_rate"], marker="o", label="Actual")
plt.plot(calibration.index, calibration["prediction"], marker="o", label="Predicted")
plt.xlabel("Positive Rate Bin")
plt.ylabel("Mean Value")
plt.title("Calibration by Positive Rate Bin")
plt.legend()
plt.grid(True)
plt.show()

# Plot 3: Residuals vs actual
residuals = plot_df["prediction"] - plot_df["pos_rate"]

plt.figure(figsize=(6, 4))
plt.scatter(plot_df["pos_rate"], residuals, alpha=0.4, s=10)
plt.axhline(0, color="black")
plt.xlabel("Actual Positive Rate")
plt.ylabel("Residual (Predicted - Actual)")
plt.title("Residuals vs Actual")
plt.grid(True)
plt.show()

