# -*- coding: utf-8 -*-
"""Pre-processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMdsgSYHjn0DANb1ExjSXeB1eQanwkeg
"""

spark

# Load the Steam reviews dataset from Google Cloud Storage into a Spark DataFrame.
# The CSV file is read with column headers enabled and Spark automatically infers
# the data types for each column based on the file contents.

df = spark.read.csv(
    "gs://game-scape/all_reviews.csv",
    header=True,
    inferSchema=True
)

df.show(5)
df.printSchema()

# This cell performs minimal, executor-safe preprocessing on the raw review dataset.
# The objective is to prepare a stable review-level dataset by:
# - Selecting only required columns to reduce memory pressure
# - Applying low-cost row-level filters (no shuffles, no regex)
# - Performing safe type casting without expensive validation
# - Creating a small set of ML-ready features
# The implementation intentionally avoids wide transformations
# (groupBy, dropDuplicates, count) to prevent executor termination.

from pyspark.sql.functions import col, length, from_unixtime, when

# Select only required columns to reduce I/O and serialization overhead
silver_df = df.select(
    "appid",
    "game",
    "review",
    "voted_up",
    "author_playtime_at_review",
    "timestamp_created",
    "language"
)

# Filter to English reviews and remove empty or null text
silver_df = silver_df.filter(
    (col("language") == "english") &
    col("review").isNotNull() &
    (length(col("review")) > 0)
)

# Perform lightweight type casting without regex validation
silver_df = silver_df \
    .withColumn("appid", col("appid").cast("int")) \
    .withColumn("voted_up", col("voted_up").cast("int")) \
    .withColumn("playtime_hours",
                col("author_playtime_at_review").cast("double") / 60.0) \
    .withColumn("created_date",
                from_unixtime(col("timestamp_created").cast("long"))) \
    .withColumn("is_positive",
                when(col("voted_up") == 1, 1.0).otherwise(0.0))

# Drop rows where critical casting failed
silver_df = silver_df.filter(col("appid").isNotNull())

# Trigger a small bounded action to validate execution without full scan
silver_df.limit(5).show(truncate=30)

# This cell stabilizes the cleaned review-level dataset in memory/disk
# and performs a lightweight sanity validation.
# Persisting avoids recomputation and executor churn in later stages.
# Only bounded actions are used to prevent kernel termination.

from pyspark.storagelevel import StorageLevel

# Persist to disk-first to stay within memory and CPU quota limits
silver_df = silver_df.persist(StorageLevel.DISK_ONLY)

# Small action to materialize the DAG safely
silver_df.select(
    "appid",
    "game",
    "is_positive",
    "playtime_hours",
    "created_date"
).limit(10).show(truncate=30)

from pyspark.sql.functions import avg, count, sum, min, max, col

# Repartition once to control shuffle
silver_df = silver_df.repartition(200, "appid")

# Game-level aggregation
gold_df = (
    silver_df
    .groupBy("appid", "game")
    .agg(
        avg("is_positive").alias("pos_rate"),
        count("*").alias("review_count"),
        sum("is_positive").alias("positive_reviews"),
        avg("playtime_hours").alias("avg_playtime_hours"),
        min("created_date").alias("first_review_date"),
        max("created_date").alias("last_review_date")
    )
)

# Persist to avoid recomputation
from pyspark.storagelevel import StorageLevel
gold_df = gold_df.persist(StorageLevel.DISK_ONLY)

# Small, safe validation
gold_df.orderBy(col("review_count").desc()).limit(10).show(truncate=30)

# This cell writes the aggregated game-level (Gold layer) dataset to
# Google Cloud Storage in columnar Parquet format for efficient storage
# and downstream analytics or ML consumption.

gold_output_path = "gs://game-scape/gold/game_level_metrics"

gold_df.write \
    .mode("overwrite") \
    .parquet(gold_output_path)

print(f"Gold dataset written to {gold_output_path}")

gold_df.printSchema()
gold_df.count()

from pyspark.sql.functions import col, split, lower
from pyspark.ml.feature import CountVectorizer

# Read Steam metadata
meta_df = spark.read.csv(
    "gs://game-scape/steam.csv",
    header=True,
    inferSchema=True
)

# Keep only required columns for ML
meta_df = meta_df.select(
    "appid",
    "categories",
    "genres",
    "steamspy_tags",
    "price",
    "required_age",
    "owners",
    "positive_ratings",
    "negative_ratings",
    "average_playtime",
    "median_playtime"
)

# Normalize and split multi-valued categorical columns
meta_df = (
    meta_df
    .withColumn("genres_arr", split(lower(col("genres")), ";"))
    .withColumn("categories_arr", split(lower(col("categories")), ";"))
    .withColumn("tags_arr", split(lower(col("steamspy_tags")), ";"))
)

# Multi-hot encode genres
genres_cv = CountVectorizer(
    inputCol="genres_arr",
    outputCol="genres_vec",
    minDF=100
)
genres_model = genres_cv.fit(meta_df)
meta_df = genres_model.transform(meta_df)

# Multi-hot encode categories
categories_cv = CountVectorizer(
    inputCol="categories_arr",
    outputCol="categories_vec",
    minDF=100
)
categories_model = categories_cv.fit(meta_df)
meta_df = categories_model.transform(meta_df)

# Multi-hot encode SteamSpy tags
tags_cv = CountVectorizer(
    inputCol="tags_arr",
    outputCol="tags_vec",
    minDF=200
)
tags_model = tags_cv.fit(meta_df)
meta_df = tags_model.transform(meta_df)

# Select final metadata features for ML and joining
meta_encoded_df = meta_df.select(
    col("appid").cast("int"),
    "genres_vec",
    "categories_vec",
    "tags_vec",
    col("price").cast("double"),
    col("required_age").cast("int"),
    col("positive_ratings").cast("int"),
    col("negative_ratings").cast("int"),
    col("average_playtime").cast("int"),
    col("median_playtime").cast("int")
)

# Materialize once to stabilize downstream joins
meta_encoded_df = meta_encoded_df.persist()

meta_encoded_df.printSchema()
meta_encoded_df.count()

# This cell joins the Gold-layer game metrics with encoded metadata
# and assembles all numerical and multi-hot encoded features into a
# single ML-ready feature vector.
#
# Output:
# - One row per appid (game)
# - Label column: pos_rate
# - Feature vector: numerical metrics + multi-hot encoded metadata
# - Ready for Spark ML models (regression / classification)

from pyspark.ml.feature import VectorAssembler

# Join Gold metrics with encoded metadata

final_df = (
    gold_df
    .join(meta_encoded_df, on="appid", how="inner")
)


# Select feature columns

numeric_features = [
    "review_count",
    "positive_reviews",
    "avg_playtime_hours",
    "average_playtime",
    "median_playtime",
    "price",
    "required_age"
]

vector_features = [
    "genres_vec",
    "categories_vec",
    "tags_vec"
]

# Assemble features into a single vector

assembler = VectorAssembler(
    inputCols=numeric_features + vector_features,
    outputCol="features",
    handleInvalid="skip"
)

ml_df = assembler.transform(final_df)

# Final ML dataset

ml_df = ml_df.select(
    "appid",
    "game",
    "pos_rate",     # label
    "features"      # ML input
)

# Materialize once to avoid recomputation
ml_df = ml_df.persist()

print(f"Final ML rows: {ml_df.count():,}")
ml_df.printSchema()

(
    final_df
    .coalesce(1)
    .write
    .mode("overwrite")
    .parquet("gs://game-scape/gold/final_ml_dataset_single")
)

# This cell extracts a driver-safe numeric subset of ML features
# for exploratory visualization and sanity checking.

plot_df = (
    final_df
    .select(
        "pos_rate",
        "review_count",
        "avg_playtime_hours",
        "price",
        "required_age",
        "positive_ratings",
        "negative_ratings"
    )
    .filter(col("review_count") >= 100)   # remove noisy low-sample games
    .limit(3000)                          # hard cap to protect kernel
    .toPandas()
)

# This plot visualizes the distribution of the target variable (positive review rate).
# It helps validate that the regression target is continuous, bounded, and not degenerate.

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 4))
sns.histplot(plot_df["pos_rate"], bins=30)
plt.title("Distribution of Positive Review Rate")
plt.xlabel("Positive Review Rate")
plt.ylabel("Number of Games")
plt.show()

